// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/ranggabudipangestu/simple-ecommerce/internal/app/order/dto"
	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, payload
func (_m *OrderService) CreateOrder(ctx context.Context, payload dto.CreateOrderDto) (interface{}, error, string) {
	ret := _m.Called(ctx, payload)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateOrderDto) interface{}); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateOrderDto) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	var r2 string
	if rf, ok := ret.Get(2).(func(context.Context, dto.CreateOrderDto) string); ok {
		r2 = rf(ctx, payload)
	} else {
		r2 = ret.Get(2).(string)
	}

	return r0, r1, r2
}

// GetOrderDetails provides a mock function with given fields: ctx, id
func (_m *OrderService) GetOrderDetails(ctx context.Context, id int) (*dto.GetOrderDto, error, string) {
	ret := _m.Called(ctx, id)

	var r0 *dto.GetOrderDto
	if rf, ok := ret.Get(0).(func(context.Context, int) *dto.GetOrderDto); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetOrderDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	var r2 string
	if rf, ok := ret.Get(2).(func(context.Context, int) string); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Get(2).(string)
	}

	return r0, r1, r2
}

type mockConstructorTestingTNewOrderService interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderService(t mockConstructorTestingTNewOrderService) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
